# Generated by Django 5.1.1 on 2024-11-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TryOnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_image", models.ImageField(upload_to="person_images/")),
                ("garment_image", models.ImageField(upload_to="garment_images/")),
                ("garment_description", models.TextField()),
                (
                    "result_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="result_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
